### ISSUE TITLE
 JSON parsing failure at character 1:'C' in Connection Failure

### ISSUE THREAD

**Issue by ef1972** [jcberquist/stripecfc#2]
I get the following error JSON parsing failure at character 1:'C' in Connection Failure when running the sample codel.

**Comment by jcberquist** [comment]
So this error happens because stripe.cfc is not getting an answer from the stripe api, it is actually failing to connect to it and so the http response body is "Connection Failure" which is not valid JSON, obviously. I should definitely look into handling an error like this better, and not try to parse the response if it is not JSON.

But as to the error itself, you can check out the following link:
https://groups.google.com/a/lists.stripe.com/forum/#!msg/api-discuss/HXtnBXV_0Go/w4W899kkF9YJ
and following out the link given there:
http://www.raymondcamden.com/2011/01/12/Diagnosing-a-CFHTTP-issue-peer-not-authenticated
http://www.mischefamily.com/nathan/index.cfm/2010/4/16/OpenID-And-ColdFusion

**Comment by ef1972** [comment]
Do I need to use ssl in my test environment to get stripe.cfc to work?

**Comment by jcberquist** [comment]
The stripe api is only accessible via an ssl connection

**Comment by ef1972** [comment]
even in test mode?

**Comment by ef1972** [comment]
The stripe documentation says you can test without ssl

https://stripe.com/help/ssl

**Comment by jcberquist** [comment]
I would try something like the following code when using stripe.cfc in a request to verify if this is the issue:
```
objSecurity = createObject("java", "java.security.Security");
objSecurity.removeProvider("JsafeJCE");
stripe = new path.to.stripe( "STRIPE_TESTING_KEY" );
card =  { number = "4242424242424242", exp_month = 5, exp_year = 2016 };
charge = stripe.createCharge( amount = 2000, card = card );
writeDump( charge );
```
If that works, then the issue is the one discussed in the above links. 

I don't think the docs are referring to connecting to their api, which is only accessible via HTTPS but rather to your own site from which you are connecting to their api.

**Comment by ef1972** [comment]
Seems to work. I am able to dump the object and the transaction shows up in
my stripe dashboard.  Thanks.

**Comment by jcberquist** [comment]
Glad it is working. I would like to point out two things: Those links specify that this is only an issue on CF9 Enterprise and Developer (not CF9 standard) so if your production machine is running CF9 standard you wouldn't need to remove the JsafeJCE provider on it. Also you shouldn't need to remove the provider over and over on each request, the comment where I got that code from specified that they ran it only in their onApplicationStart() method.
